#BNF+IAT 1.0 UTF-8;
!grammar talkgo;
!slot <dial>;
!slot <msg>;
!slot <want>;
!slot <precall>;
!slot <sufcall>;
!slot <presms>;
!slot <sufsms>;
!slot <preapp>;
!slot <app>;
!slot <contact>;
!start <action>;
<action>:<openapp>|<sms>|<call>;
<call>:<dial>|<dialcontact>;
<dialcontact>:[<want>]<precall><contact>[<sufcall>];
<sms>:<msg>|<msgcontact>;
<msgcontact>:[<want>]<presms><contact>[<sufsms>];
<openapp>:<preapp><app>;

<dial>:打电话|打个电话|我想打电话|我要打电话;
<msg>:发短信|编辑短信|我要发短信|我想发短信;
<want>:我想|我要|帮我;
<precall>:给|打电话给|打个电话给|呼叫|拨打;
<sufcall>:打电话|打个电话|的号码|的手机|的电话;
<presms>:给|发短信给|发个短信给;
<sufsms>:发个短信|发短信;
<preapp>:打开|启动|打开应用|启动应用|打开软件|启动软件;
<app>:应用名称|微信;
<contact>:联系人|张三;
